Controllers/Hospital/HospitalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalManagementSystem.Controllers.Hospital
{
    public class HospitalController : Controller
    {
        // GET: Hospital
        public ActionResult hospital()
        {
            return View();
        }
    }
}

Views/Hospital/hospital.cshtml
@model HospitalManagementSystem.ViewModel.HospitalViewModel
@using HospitalManagementSystem.Common;
@{
    ViewBag.Title = "hospital";
}





<section class="content-header">
    <h1>
        Hospital Management
        <small>Registration</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Home/Index"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/Hospital/hospital">Hospital Registration</a></li>
        @*<li class="active">General Elements</li>*@
    </ol>
</section>
<section class="content">
    <div class="row">

        <div class="col-md-12">

            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Hospital Registration</h3>
                </div>

                @using (Html.BeginForm("hospital", "Hospital", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@

            <div class="box-body">


                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(m => m.HospitalName, new { @class = "col-sm-3 control-label " })

                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.HospitalName, new { placeholder = "Hospital Name", @maxlength = "20", @class = "form-control " })

                                @Html.ValidationMessageFor(m => m.HospitalName, "", new { @class = "text-danger " })
                            </div>
                        </div>



                        <div class="form-group">
                            @Html.LabelFor(m => m.Email, new { @class = "col-sm-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.Email, new { placeholder = "Email", @maxlength = "50", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>





                        <div class="form-group">
                            @Html.LabelFor(m => m.ContactNo, new { @class = "col-sm-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.ContactNo, new { placeholder = "Contact No", @maxlength = "10", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.ContactNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.ContactPerson, new { @class = "col-sm-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.ContactPerson, new { placeholder = "Contact Person", @maxlength = "20", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.ContactPerson, "", new { @class = "text-danger" })
                            </div>
                        </div>







                        <div class="form-group">
                            @Html.LabelFor(m => m.HospitalPhoneNumber, new { @class = "col-sm-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.HospitalPhoneNumber, new { placeholder = "Hospital Phone Number", @maxlength = "10", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.HospitalPhoneNumber, "", new { @class = "text-danger" })

                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(m => m.ChartNumber, new { @class = "col-sm-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.ChartNumber, new { placeholder = "Chart Number", @maxlength = "20", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.ChartNumber, "", new { @class = "text-danger" })

                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(m => m.HealthCareNumber, new { @class = "col-sm-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.HealthCareNumber, new { placeholder = "Health Care Number", @maxlength = "10", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.HealthCareNumber, "", new { @class = "text-danger" })

                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.HospitalAddress, new { @class = "col-sm-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.HospitalAddress, new { placeholder = "Hospital Address", @maxlength = "100", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.HospitalAddress, "", new { @class = "text-danger" })

                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Address, new { @class = "col-sm-3 control-label" })
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.Address, new { placeholder = "Street Address", @maxlength = "100", @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })<br />
                                <div class="row">
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(m => m.City, new { placeholder = "city", @maxlength = "20", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.City, "", new { @class = "text-danger" })<br />
                                        @Html.TextBoxFor(m => m.PostalCode, new { placeholder = "ZIP/Postal Code", @maxlength = "10", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.PostalCode, "", new { @class = "text-danger" })<br />
                                    </div>
                                    <div class="col-md-6">
                                        @Html.TextBoxFor(m => m.State, new { placeholder = "State", @maxlength = "20", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.State, "", new { @class = "text-danger" })<br />
                                        @*@Html.DropDownListFor(m => m.Country, Model.CountryList, "Select your Country", new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Country, "", new { @class = "text-danger" })*@
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

                <div class="box-footer">
                    <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-5"><button class="btn btn-gradgreen pull-left " type="submit"><i class="fa fa-plus-square"></i> SAVE </button></div>
                        <div class="col-md-3"><button class="btn btn-gradgray pull-right" type="reset"><i class="fa fa-refresh"></i> Reset</button></div>
                    </div>
                </div>

                  }
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}