Controllers/Medicine/MedicineController.cs
using HospitalManagementSystem.Common;
using HospitalManagementSystem.DataAccess.Repository;
using HospitalManagementSystem.JqGrid;
using HospitalManagementSystem.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalManagementSystem.Controllers
{
    public class MedicineController : Controller
    {
        // GET: Medicine
        public ActionResult Index()
        {
            return View();
        }
        public List<SelectListItem> CategoryList { get;  set; }
        public ActionResult Add()
        {
           
            var ViewModel = new MedicineViewModel();

            ViewModel.CategoryList = GetCategoryList();

            return View(ViewModel);
        }
       
        private List<SelectListItem> GetCategoryList()
        {
            var categorySelectList = new List<SelectListItem>();
            var mastercategoryRepository = new MasterCategoryRepository();
            var categoryList = mastercategoryRepository.GetCategoryList();

            foreach (var item in categoryList)
            {
                categorySelectList.Add(new SelectListItem() { Text = item.Description, Value = item.CategoryId.ToString() });
            }
            return categorySelectList;
        }
        public ActionResult AddMedicine(MedicineViewModel model)
        {

            var medicineRepository = new MedicineRepository();
            if (model.MedicineId == default(int))
            {
                medicineRepository.MedicineDetailInsertion(model);
                TempData[AppConstant.Response] = AppConstant.Success;
                return RedirectToAction("Add");
            }
            else
            {


                medicineRepository.MedicineDetailUpdation(model);
                TempData[AppConstant.Response] = AppConstant.Success;
                return RedirectToAction("Index");
            }

            return View();

        }
        public ActionResult GetMedicineList(JQGridSort jQGridSort)
        {
            var medicineRepository = new MedicineRepository();
            var result = medicineRepository.GetMedicineList(jQGridSort);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int medicineId)
        {
            var medicineRepository = new MedicineRepository();
            medicineRepository.MedicineDeletion(medicineId);
            return Json(new AjaxResponse() { IsSuccess = true });
        }

        public ActionResult UpdateMedicineDetail(string id = null)
        {
            int medicineId = default(int);

            if (!string.IsNullOrEmpty(id))
            {
                int.TryParse(Cryptography.DecryptStringFromBytes_Aes(id), out medicineId);
            }

            var model = new MedicineViewModel();
            var medicineRepository = new MedicineRepository();

            model = medicineRepository.GetMedicineByMedicineDetailId(medicineId);

            model.CategoryList = GetCategoryList();

            return View(model);

        }
        public ActionResult GetMedicineDetail(string id)
        {
            int medicineId = default(int);
            if (!string.IsNullOrEmpty(id))
            {
                int.TryParse(Cryptography.DecryptStringFromBytes_Aes(id), out medicineId);
            }
            var medicineRepository = new MedicineRepository();
            var result = medicineRepository.GetMedicineDetail(medicineId);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

Views/Medicine/Add.cshtml
@model HospitalManagementSystem.ViewModel.MedicineViewModel
@using HospitalManagementSystem.Common;
@{
    ViewBag.Title = "Add";
}

<section class="content-header">
    <h1>
        Medicine Management
        <small>Registration</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Home/Index"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/Medicine/Add">Medicine Registration</a></li>
        @*<li class="active">General Elements</li>*@
    </ol>
</section>
<section class="content">
    <div class="row">

        <div class="col-md-12">

            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Medicine Registration</h3>
                </div>

                @using (Html.BeginForm("AddMedicine", "Medicine", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@

                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.MedicineName, new { @class = "col-sm-3 control-label " })
                                    <div class="col-sm-9">
                                        @Html.TextBoxFor(m => m.MedicineName, new { placeholder = "Medicine Name", @maxlength = "20", @class = "form-control " })
                                        @Html.ValidationMessageFor(m => m.MedicineName, "", new { @class = "text-danger " })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Category, htmlAttributes: new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(m => m.Category, Model.CategoryList, "Select Catogory", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Category, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyName, new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(m => m.CompanyName, new { placeholder = "Company Name", @maxlength = "20", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.CompanyName, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.PurchaseDate, new { placeholder = "Date of Birth", @maxlength = "15", htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Price, new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(m => m.Price, new { placeholder = "Price", @maxlength = "10", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.ExpiredDate, htmlAttributes: new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.ExpiredDate, new { placeholder = "Date of Birth", @maxlength = "15", htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ExpiredDate, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(m => m.Stock, new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(m => m.Stock, new { placeholder = "Stock", @maxlength = "5", @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Stock, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="box-footer">
                        <div class="row">
                            <div class="col-md-1"></div>
                            <div class="col-md-5">  <button class="btn btn-gradgreen pull-left" type="submit"><i class="fa fa-plus-square"></i> SAVE </button></div>
                            <div class="col-md-3">  <button class="btn btn-gradgray pull-right" type="reset"><i class="fa fa-refresh"></i> Reset</button></div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>

    $(document).ready(function () {
        $('input[type=datetime]').datepicker({
            dateFormat: "dd-mm-yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "-60:+0",
             onSelect: function (dateString, txtDate) {
                alert("Selected Date: " + dateString + "\nTextBox ID: " + txtDate.id);
            }
        });

    });
</script>

Views/Medicine/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<style>

    .border-right {
        border-right: 1px solid #dee2e6 !important;
    }

    .form-control[disabled], .form-control[readonly], fieldset[disabled] {
        background-color: #fff;
    }
</style>

<div class="panel">

    <div class="panel panel-info">
        <div class="panel-heading">Medicine Details</div>
        <div class="panel-body">
            <table id="jqMedicineGrid"></table>
            <div id="jqMedicineGridPager"></div>

        </div>
    </div>
</div>
<script src="~/Scripts/Medicine/Medicine.js"></script>

<section class="content">
    <div class="modal fade" id="MedicineDetailModalPopup">
        <div class="modal-dialog box box-info" style="width:80%;">
            <div class="modal-content ">
                <div class="box-header with-border">
                    <h3 class="box-title" id="ProfileTitle"></h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-dismiss="modal" aria-label="Close"><i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-3 border-right">
                                @*<div class="d-flex flex-column align-items-center text-center p-3 py-5">
                                    <img class="rounded-circle mt-5 image" id="ProfileImage" style="max-width:220px" src="">
                                </div>*@
                            </div>
                            <div class="col-md-5 border-right">
                                <div class="p-3 py-5  form-group">

                                   
                                    <div class="row md-3 form-group">
                                        <div class="col-md-12 form-group"><label class="labels">Medicine Name</label><input type="text" id="MedicineName" class="form-control" readonly></div>
                                        <div class="col-md-12 form-group"><label class="labels">Category</label><input type="text" id="Category" class="form-control" readonly></div>
                                        <div class="col-md-12 form-group"><label class="labels">Company Name</label><input type="text" id="CompanyName" class="form-control" readonly></div>
                                        <div class="col-md-12 form-group"><label class="labels">Price</label><input type="text" id="Price" class="form-control" readonly></div>


                                    </div>
                                    @*<div class="row md-3 form-group">

                                        </div>*@
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="p-3 py-5">
                                    <div class="col-md-12 form-group"><label class="labels">Purchase Date</label><input type="text" id="PurchaseDate" class="form-control" readonly></div> <br>
                                    <div class="col-md-12 form-group"><label class="labels">Expired Date</label><input type="text" id="ExpiredDate" class="form-control" readonly></div>
                                    <div class="col-md-12 form-group"><label class="labels">Stock</label><input type="text" id="Stock" class="form-control" readonly></div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>



</section>
@*<script type="text/javascript">
    $(document).ready(function () {
        $('#DateofAppointment').datepicker({
            dateFormat: "dd/mm/yy",
            showStatus: true,
            showWeeks: true,
            currentText: 'Now',
            autoSize: true,
            gotoCurrent: true,
            showAnim: 'blind',
            highlightWeek: true
        });
    });
</script>*@

Views/Medicine/UpdateMedicineDetail.cshtml
@model HospitalManagementSystem.ViewModel.MedicineViewModel
@using HospitalManagementSystem.Common;
@{
    ViewBag.Title = "Add";
}

<section class="content-header">
    <h1>
        Medicine Management
        <small>Registration</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Home/Index"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/Medicine/Add">MedicineRegistration</a></li>
        @*<li class="active">General Elements</li>*@
    </ol>
</section>
<section class="content">
    <div class="row">

        <div class="col-md-12">

            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Medicine Registration</h3>
                </div>

                @using (Html.BeginForm("AddMedicine", "Medicine", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.MedicineId, new { @class = "form-control" })

                    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@

                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(m => m.MedicineName, new { @class = "col-sm-3 control-label " })
                                    <div class="col-sm-9">
                                        @Html.TextBoxFor(m => m.MedicineName, new { placeholder = "Medicine Name", @maxlength = "20", @class = "form-control " })
                                      
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Category, htmlAttributes: new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(m => m.Category, Model.CategoryList, "Select Catogory", new { @class = "form-control" })
                                     
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(m => m.CompanyName, new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(m => m.CompanyName, new { placeholder = "Company Name", @maxlength = "20", @class = "form-control" })
                                     
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.PurchaseDate, new { placeholder = "Date of Birth", @maxlength = "15", htmlAttributes = new { @class = "form-control" } })
                                      
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">

                                <div class="form-group">
                                    @Html.LabelFor(m => m.Price, new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(m => m.Price, new { placeholder = "Price", @maxlength = "10", @class = "form-control" })
                                      
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.ExpiredDate, htmlAttributes: new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.ExpiredDate, new { placeholder = "Date of Birth", @maxlength = "15", htmlAttributes = new { @class = "form-control" } })
                                     
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(m => m.Stock, new { @class = "col-sm-3 control-label" })
                                    <div class="col-md-9">
                                        @Html.TextBoxFor(m => m.Stock, new { placeholder = "Stock", @maxlength = "5", @class = "form-control" })
                                       
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="box-footer">
                        <div class="row">
                            <div class="col-md-1"></div>
                            <div class="col-md-5">  <button class="btn btn-gradgreen pull-left" type="submit"><i class="fa fa-plus-square"></i> SAVE </button></div>
                            <div class="col-md-3">  <button class="btn btn-gradgray pull-right" type="reset"><i class="fa fa-refresh"></i> Reset</button></div>
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>


</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>

    $(document).ready(function () {
        $('input[type=datetime]').datepicker({
            dateFormat: "dd-mm-yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "-60:+0",
             onSelect: function (dateString, txtDate) {
             /*   alert("Selected Date: " + dateString + "\nTextBox ID: " + txtDate.id);*/
            }
        });

    });
</script>